"""
convert_weights_to_mif.py

Converts extracted .npy weight files → Quartus MIF format
for BRAM initialization on Stratix III (DE3-340).

MIF Format:
  - Intel/Altera Memory Initialization File
  - Used by Quartus to pre-load BRAM contents
  - Each weight quantized to INT8 (signed, -128 to 127)
  - Stored as 8-bit hex values

Output structure:
  rtl_design_files/mif/
  ├── layer_000_Conv_32x3_3x3_w.mif
  ├── layer_000_Conv_32x3_3x3_b.mif
  ├── layer_001_DWConv_32x1_3x3_w.mif
  ├── ...
  └── bram_summary.csv   ← M9K block usage per layer
"""

import numpy as np
import os
import csv
import json

WEIGHTS_DIR = "rtl_design_files/weights"
MIF_DIR     = "rtl_design_files/mif"
ARCH_CSV    = "rtl_design_files/sffn_architecture.csv"
QUANT_JSON  = "rtl_design_files/quantization_params.json"

os.makedirs(MIF_DIR, exist_ok=True)

# ── Quantization helper ───────────────────────────────────────────────────────
def quantize_to_int8(weights: np.ndarray, scale: float = None) -> tuple:
    """
    Quantize FP32 weights to INT8.
    If scale is provided (from NNCF), use it.
    Otherwise compute per-tensor symmetric scale.
    Returns (int8_array, scale_used, zero_point)
    """
    if scale is None:
        # Per-tensor symmetric quantization
        max_val = np.max(np.abs(weights))
        scale   = max_val / 127.0 if max_val > 0 else 1.0

    zero_point = 0  # symmetric → zero point = 0
    quantized  = np.clip(np.round(weights / scale), -128, 127).astype(np.int8)
    return quantized, scale, zero_point

# ── MIF file writer ───────────────────────────────────────────────────────────
def write_mif(data: np.ndarray, filepath: str, data_width: int = 8):
    """
    Write a numpy array as a Quartus .mif file.

    MIF file structure:
      WIDTH    = 8;        -- bits per word (INT8)
      DEPTH    = N;        -- number of words
      ADDRESS_RADIX = HEX;
      DATA_RADIX    = HEX;
      CONTENT BEGIN
        0000 : FF;         -- address : data
        ...
      END;
    """
    flat   = data.flatten()
    depth  = len(flat)
    addr_w = max(4, len(hex(depth - 1)) - 2)  # hex address width

    with open(filepath, 'w') as f:
        f.write(f"-- Quartus MIF for Stratix III BRAM initialization\n")
        f.write(f"-- Generated by convert_weights_to_mif.py\n")
        f.write(f"-- Shape: {data.shape}  |  Elements: {depth}\n")
        f.write(f"-- Layout: [out_ch, in_ch, kH, kW] flattened row-major\n\n")
        f.write(f"WIDTH = {data_width};\n")
        f.write(f"DEPTH = {depth};\n\n")
        f.write(f"ADDRESS_RADIX = HEX;\n")
        f.write(f"DATA_RADIX = HEX;\n\n")
        f.write(f"CONTENT BEGIN\n")

        for addr, val in enumerate(flat):
            # Convert signed int8 to unsigned hex (two's complement)
            hex_val = format(int(val) & 0xFF, '02X')
            hex_addr = format(addr, f'0{addr_w}X')
            f.write(f"\t{hex_addr} : {hex_val};\n")

        f.write(f"END;\n")

# ── COE file writer (Xilinx alternative, useful for reference) ────────────────
def write_coe(data: np.ndarray, filepath: str):
    """
    Write Xilinx COE format (included as reference only).
    Primary target is MIF for Quartus/Stratix III.
    """
    flat = data.flatten()
    with open(filepath, 'w') as f:
        f.write("memory_initialization_radix=16;\n")
        f.write("memory_initialization_vector=\n")
        hex_vals = [format(int(v) & 0xFF, '02x') for v in flat]
        f.write(',\n'.join(hex_vals) + ';\n')

# ── M9K block calculator ──────────────────────────────────────────────────────
def calc_m9k_blocks(num_elements: int, data_width: int = 8) -> int:
    """
    Calculate M9K blocks needed for Stratix III.
    Each M9K = 9,216 bits = 1,024 x 9-bit words (or 256 x 36-bit etc.)
    For 8-bit data: 1,024 words per M9K block.
    """
    words_per_m9k = 1024  # at 8-bit width
    return max(1, int(np.ceil(num_elements / words_per_m9k)))

# ── Load quantization params ──────────────────────────────────────────────────
quant_params = {}
if os.path.exists(QUANT_JSON):
    with open(QUANT_JSON) as f:
        qdata = json.load(f)
    quant_params = qdata.get("scales", {})
    print(f"Loaded {len(quant_params)} quantization scale factors")
else:
    print("No quantization JSON found — using per-tensor auto scaling")

# ── Main conversion loop ──────────────────────────────────────────────────────
print("=" * 70)
print("CONVERTING WEIGHTS TO MIF FORMAT (Quartus / Stratix III)")
print("=" * 70)

npy_files    = sorted([f for f in os.listdir(WEIGHTS_DIR) if f.endswith('.npy')])
bram_summary = []
total_m9k    = 0
total_params = 0

print(f"\nFound {len(npy_files)} weight files to convert\n")
print(f"{'File':<55} {'Shape':<20} {'Elements':>10} {'M9K':>6} {'Scale':>12}")
print("-" * 110)

for npy_file in npy_files:
    npy_path = os.path.join(WEIGHTS_DIR, npy_file)
    weights  = np.load(npy_path)

    # Determine if bias or weight
    is_bias = npy_file.endswith('_b.npy')

    # Quantize to INT8
    # Biases are typically kept at higher precision — store as INT16 or FP32
    # For simplicity and Stratix III compatibility, we quantize biases to INT16
    if is_bias:
        # INT16 bias (common practice — avoids bias quantization error)
        scale      = np.max(np.abs(weights)) / 32767.0 if np.max(np.abs(weights)) > 0 else 1.0
        quantized  = np.clip(np.round(weights / scale), -32768, 32767).astype(np.int16)
        data_width = 16
        zero_point = 0
    else:
        quantized, scale, zero_point = quantize_to_int8(weights)
        data_width = 8

    # Output MIF filename
    mif_name = npy_file.replace('.npy', '.mif')
    mif_path = os.path.join(MIF_DIR, mif_name)

    # Write MIF
    write_mif(quantized, mif_path, data_width=data_width)

    # Write COE as reference
    if not is_bias:
        coe_path = mif_path.replace('.mif', '.coe')
        write_coe(quantized, coe_path)

    # Calculate M9K usage
    num_elements = quantized.size
    m9k_blocks   = calc_m9k_blocks(num_elements, data_width)
    total_m9k   += m9k_blocks
    total_params += num_elements

    # Log
    shape_str = str(weights.shape)
    print(f"  {npy_file:<55} {shape_str:<20} {num_elements:>10,} {m9k_blocks:>6} {scale:>12.6f}")

    bram_summary.append({
        "npy_file"    : npy_file,
        "mif_file"    : mif_name,
        "shape"       : str(weights.shape),
        "elements"    : num_elements,
        "data_width"  : data_width,
        "scale"       : round(float(scale), 8),
        "zero_point"  : int(zero_point) if not is_bias else 0,
        "m9k_blocks"  : m9k_blocks,
        "size_kb"     : round(num_elements * data_width / 8 / 1024, 3),
    })

# ── Save BRAM summary CSV ─────────────────────────────────────────────────────
summary_csv = os.path.join("rtl_design_files", "bram_summary.csv")
with open(summary_csv, 'w', newline='') as f:
    writer = csv.DictWriter(f, fieldnames=bram_summary[0].keys())
    writer.writeheader()
    writer.writerows(bram_summary)

# ── Write RTL parameter header file ──────────────────────────────────────────
"""
Generates a SystemVerilog package file with all layer parameters.
This can be `import`ed into your RTL modules directly.
"""
sv_pkg = os.path.join("rtl_design_files", "sffn_params_pkg.sv")
with open(sv_pkg, 'w') as f:
    f.write("// Auto-generated SystemVerilog parameter package\n")
    f.write("// SFFN INT8 model — Stratix III DE3-340\n")
    f.write("// Generated by convert_weights_to_mif.py\n\n")
    f.write("package sffn_params;\n\n")
    f.write(f"  // Model summary\n")
    f.write(f"  parameter int NUM_CONV_LAYERS  = 84;\n")
    f.write(f"  parameter int TOTAL_PARAMS     = {total_params};\n")
    f.write(f"  parameter int WEIGHT_BITS      = 8;   // INT8\n")
    f.write(f"  parameter int BIAS_BITS        = 16;  // INT16\n")
    f.write(f"  parameter int ACCUM_BITS       = 32;  // accumulator width\n")
    f.write(f"  parameter int INPUT_H          = 224;\n")
    f.write(f"  parameter int INPUT_W          = 224;\n")
    f.write(f"  parameter int SPATIAL_IN_CH    = 3;   // spatial_in\n")
    f.write(f"  parameter int FREQ_IN_CH       = 2;   // freq_in\n")
    f.write(f"  parameter int NUM_CLASSES      = 2;   // fake / real\n\n")

    f.write(f"  // Stratix III BRAM usage\n")
    f.write(f"  parameter int M9K_TOTAL_AVAIL  = 9383;  // EP3SL340\n")
    f.write(f"  parameter int M9K_WEIGHTS_USED = {total_m9k};\n")
    f.write(f"  parameter real M9K_UTILIZATION = {total_m9k/9383*100:.1f}; // percent\n\n")

    f.write(f"  // Quantization scale factors (from NNCF)\n")
    f.write(f"  parameter int NUM_QUANT_SCALES = 16;\n\n")

    # Write per-layer parameters
    f.write(f"  // Per-layer channel dimensions\n")
    layer_configs = [
        ("L000", 32,   3,   3, 3, "spatial  - stem conv"),
        ("L001", 32,   32,  1, 3, "spatial  - DW 3x3"),
        ("L002", 8,    32,  1, 1, "spatial  - PW 1x1"),
        ("L081", 32,   2,   1, 3, "frequency - conv0"),
        ("L082", 64,   32,  1, 3, "frequency - conv1"),
        ("L083", 2,    128, 1, 3, "recon_head - output conv"),
    ]
    for name, oc, ic, g, k, comment in layer_configs:
        f.write(f"  // {comment}\n")
        f.write(f"  parameter int {name}_OUT_CH = {oc};\n")
        f.write(f"  parameter int {name}_IN_CH  = {ic};\n")
        f.write(f"  parameter int {name}_GROUPS = {g};\n")
        f.write(f"  parameter int {name}_KERNEL = {k};\n\n")

    f.write("endpackage : sffn_params\n")

# ── Final summary ─────────────────────────────────────────────────────────────
print("\n" + "=" * 70)
print("CONVERSION COMPLETE")
print("=" * 70)
print(f"\n  MIF files generated : {len([b for b in bram_summary if b['mif_file'].endswith('.mif')])}")
print(f"  Total parameters    : {total_params:,}")
print(f"  Total INT8 size     : {total_params/1024:.1f} KB")
print(f"  M9K blocks used     : {total_m9k:,} / 9,383")
print(f"  M9K utilization     : {total_m9k/9383*100:.1f}%  (weights only)")
print(f"  Remaining M9K       : {9383-total_m9k:,}  (for feature maps + control)")
print(f"\n  Output files:")
print(f"    MIF files         : rtl_design_files/mif/")
print(f"    BRAM summary      : {summary_csv}")
print(f"    SV parameter pkg  : {sv_pkg}")
print(f"\n  Next steps in Quartus:")
print(f"    1. Create RAM megafunction block")
print(f"    2. Set 'Initialize memory content' → point to .mif file")
print(f"    3. Import sffn_params_pkg.sv into your RTL project")
print(f"    4. Use bram_summary.csv for memory map documentation")
print("=" * 70)