"""
generate_sim_weights.py
Loads real INT8 weights from .npy files and generates
a SystemVerilog include file for simulation.
Covers the 4 layers used in sffn_top:
  - stem conv     (3x32x3x3)
  - freq DW conv  (2x1x3x3)
  - freq conv1    (2x32x3x3)
"""

import numpy as np
import os

WEIGHTS_DIR = "rtl_design_files/weights"
OUTPUT_FILE = "sim_weights.sv"

print("Loading weights...")

# ── Helper: load and quantize weight file ─────────────────
def load_weight(filename):
    path = os.path.join(WEIGHTS_DIR, filename)
    if not os.path.exists(path):
        print(f"  WARNING: {filename} not found, using zeros")
        return None
    w = np.load(path)
    # Already float32 — quantize to INT8
    scale = np.max(np.abs(w)) / 127.0 if np.max(np.abs(w)) > 0 else 1.0
    w_int8 = np.clip(np.round(w / scale), -128, 127).astype(np.int8)
    return w_int8

# ── Find weight files ──────────────────────────────────────
all_files = os.listdir(WEIGHTS_DIR)
weight_files = sorted([f for f in all_files if f.endswith('_w.npy')])

print(f"Found {len(weight_files)} weight files")

# ── Identify layers we need ────────────────────────────────
# Stem conv: layer_000_Conv_32x3_3x3_w.npy  shape=(32,3,3,3)
# DW conv:   layer_001_DWConv_32x1_3x3_w.npy shape=(32,1,3,3)
# Freq conv1: layer_081_Conv_32x2_3x3_w.npy  shape=(32,2,3,3)

stem_file  = None
dw_file    = None
freq1_file = None

for f in weight_files:
    if 'layer_000' in f and '_w.npy' in f:
        stem_file = f
    if 'layer_001' in f and 'DWConv' in f and '_w.npy' in f:
        dw_file = f
    if 'layer_081' in f and '_w.npy' in f:
        freq1_file = f

print(f"Stem  : {stem_file}")
print(f"DW    : {dw_file}")
print(f"Freq1 : {freq1_file}")

# ── Load weights ───────────────────────────────────────────
stem_w  = load_weight(stem_file)  if stem_file  else None
dw_w    = load_weight(dw_file)    if dw_file    else None
freq1_w = load_weight(freq1_file) if freq1_file else None

# ── Generate flat hex arrays ───────────────────────────────
def to_flat_hex(w_int8, name):
    """Convert INT8 array to flat hex string for SV"""
    flat = w_int8.flatten()
    # Convert to unsigned hex bytes
    hex_vals = [format(int(v) & 0xFF, '02x') for v in flat]
    total_bits = len(flat) * 8
    hex_str = ''.join(hex_vals)
    return total_bits, hex_str

# ── Write SystemVerilog include file ──────────────────────
with open(OUTPUT_FILE, 'w') as f:
    f.write("// ================================================\n")
    f.write("// sim_weights.sv\n")
    f.write("// Auto-generated real INT8 weights for simulation\n")
    f.write("// Generated by generate_sim_weights.py\n")
    f.write("// ================================================\n\n")

    if stem_w is not None:
        bits, hex_str = to_flat_hex(stem_w, "stem")
        f.write(f"// Stem conv weights: shape={stem_w.shape}\n")
        f.write(f"// Total bits: {bits}\n")
        f.write(f"localparam STEM_W_HEX = {bits}'h{hex_str};\n\n")
        print(f"  Stem weights: shape={stem_w.shape} bits={bits}")
    else:
        f.write("// Stem weights not found\n")
        f.write(f"localparam STEM_W_HEX = {3*32*9*8}'h0;\n\n")

    if dw_w is not None:
        # Take only first 2 channels for our DW conv (CHANNELS=2)
        dw_w_2ch = dw_w[:2]
        bits, hex_str = to_flat_hex(dw_w_2ch, "dw")
        f.write(f"// DW conv weights: shape={dw_w_2ch.shape}\n")
        f.write(f"// Total bits: {bits}\n")
        f.write(f"localparam DW_W_HEX = {bits}'h{hex_str};\n\n")
        print(f"  DW weights: shape={dw_w_2ch.shape} bits={bits}")
    else:
        f.write("// DW weights not found\n")
        f.write(f"localparam DW_W_HEX = {2*1*9*8}'h0;\n\n")

    if freq1_w is not None:
        bits, hex_str = to_flat_hex(freq1_w, "freq1")
        f.write(f"// Freq conv1 weights: shape={freq1_w.shape}\n")
        f.write(f"// Total bits: {bits}\n")
        f.write(f"localparam FREQ1_W_HEX = {bits}'h{hex_str};\n\n")
        print(f"  Freq1 weights: shape={freq1_w.shape} bits={bits}")
    else:
        f.write("// Freq1 weights not found\n")
        f.write(f"localparam FREQ1_W_HEX = {2*32*9*8}'h0;\n\n")

print(f"\nGenerated: {OUTPUT_FILE}")
print("Now update sffn_top.sv to use these weight constants")