// Auto-generated SystemVerilog parameter package
// SFFN INT8 model — Stratix III DE3-340
// Generated by convert_weights_to_mif.py

package sffn_params;

  // Model summary
  parameter int NUM_CONV_LAYERS  = 84;
  parameter int TOTAL_PARAMS     = 3988254;
  parameter int WEIGHT_BITS      = 8;   // INT8
  parameter int BIAS_BITS        = 16;  // INT16
  parameter int ACCUM_BITS       = 32;  // accumulator width
  parameter int INPUT_H          = 224;
  parameter int INPUT_W          = 224;
  parameter int SPATIAL_IN_CH    = 3;   // spatial_in
  parameter int FREQ_IN_CH       = 2;   // freq_in
  parameter int NUM_CLASSES      = 2;   // fake / real

  // Stratix III BRAM usage
  parameter int M9K_TOTAL_AVAIL  = 9383;  // EP3SL340
  parameter int M9K_WEIGHTS_USED = 3963;
  parameter real M9K_UTILIZATION = 42.2; // percent

  // Quantization scale factors (from NNCF)
  parameter int NUM_QUANT_SCALES = 16;

  // Per-layer channel dimensions
  // spatial  - stem conv
  parameter int L000_OUT_CH = 32;
  parameter int L000_IN_CH  = 3;
  parameter int L000_GROUPS = 3;
  parameter int L000_KERNEL = 3;

  // spatial  - DW 3x3
  parameter int L001_OUT_CH = 32;
  parameter int L001_IN_CH  = 32;
  parameter int L001_GROUPS = 1;
  parameter int L001_KERNEL = 3;

  // spatial  - PW 1x1
  parameter int L002_OUT_CH = 8;
  parameter int L002_IN_CH  = 32;
  parameter int L002_GROUPS = 1;
  parameter int L002_KERNEL = 1;

  // frequency - conv0
  parameter int L081_OUT_CH = 32;
  parameter int L081_IN_CH  = 2;
  parameter int L081_GROUPS = 1;
  parameter int L081_KERNEL = 3;

  // frequency - conv1
  parameter int L082_OUT_CH = 64;
  parameter int L082_IN_CH  = 32;
  parameter int L082_GROUPS = 1;
  parameter int L082_KERNEL = 3;

  // recon_head - output conv
  parameter int L083_OUT_CH = 2;
  parameter int L083_IN_CH  = 128;
  parameter int L083_GROUPS = 1;
  parameter int L083_KERNEL = 3;

endpackage : sffn_params
